import type { Category, Dish } from './types';
import { Soup, Sprout, Drumstick, Wheat, GlassWater, IceCream } from 'lucide-react';

export const categories: Category[] = [
  { id: 'starters', name: 'Starters', icon: Soup },
  { id: 'main-veg', name: 'Main Course (Veg)', icon: Sprout },
  { id: 'main-non-veg', name: 'Main Course (Non-Veg)', icon: Drumstick },
  { id: 'breads-rice', name: 'Breads & Rice', icon: Wheat },
  { id: 'beverages', name: 'Beverages', icon: GlassWater },
  { id: 'desserts', name: 'Desserts', icon: IceCream },
];

export const dishes: Dish[] = [
  // Starters
  {
    id: 1,
    name: 'Paneer Tikka',
    description: 'Marinated cottage cheese grilled in a tandoor with spices and yogurt.',
    price: 220,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxQQU5FRVIlMjBUSUtLQXxlbnwwfHx8fDE3NTMzODczMTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    video: 'https://cdn-useast1.kapwing.com/teams/68853ec45e8cd4a3b32c9e24/jobs/68853ecd6656ad59127d1dda/final_68853ec5f87e48c9a74055bc_147972.mp4?GoogleAccessId=prod-sa-videoprocessing%40kapwing-prod.iam.gserviceaccount.com&Expires=1753591711&Signature=fiLrN1Z20PNRRLjY4s8IiR7Wfhi06xeyQf7oCTd1lPqWppICYn9jFBX5PsMQu1q8dMZnGllFz9bR%2FCmxhPs9c32K4OrABRywlAWR3TUck0maAUHik8HBQHmmCgiUsYg%2BU3QFlH8VFH8ml7z7If0H%2FILBoPYzq5OeMD4tEnJKNbz4buMLdrAM86nBO1qzKZ7Y1JioOnvnUAuN2mTqqf%2FFQVTC2WRLYySQ8vI0qTHvgsMyTIJu3LlUsbXdjLM0Bg3xnxn23jRp9NeWDecedJxbpJeUZwXyjTe0cjgp0TOpdjgKTVdxKlpBQwoWK3OlX2WlevJiE8XrnzjdHFpIt8oysg%3D%3D#t=0.01',
    dataAiHint: 'paneer tikka',
    category: 'starters',
    ingredients: ['Paneer', 'Yogurt', 'Spices'],
  },
  {
    id: 2,
    name: 'Chicken Malai Tikka',
    description: 'Creamy chicken cubes marinated in cheese, cream, and cardamom.',
    price: 270,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMnx8Y2hpY2tlbiUyMGRpc2h8ZW58MHx8fHwxNzUzNDI1NzAwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/chicken-malai-tikka.mp4',
    dataAiHint: 'chicken malai tikka',
    category: 'starters',
    ingredients: ['Chicken', 'Cheese', 'Cream', 'Cardamom'],
  },
  {
    id: 3,
    name: 'Vegetable Spring Rolls',
    description: 'Crispy rolls stuffed with seasoned veggies and served with sweet chili sauce.',
    price: 180,
    image: 'https://images.unsplash.com/photo-1695712641569-05eee7b37b6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzcHJpbmclMjByb2xsfGVufDB8fHx8MTc1MzQyNTc2OXww&ixlib=rb-4.1.0&q=80&w=1080',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/samosa.mp4',
    dataAiHint: 'spring rolls',
    category: 'starters',
    ingredients: ['Mixed Vegetables', 'Flour', 'Sweet Chili Sauce'],
  },
  {
    id: 4,
    name: 'Hara Bhara Kabab',
    description: 'Spinach and peas patties blended with Indian herbs and shallow fried.',
    price: 160,
    image: 'https://images.unsplash.com/photo-1571839040405-c5d2f471ad2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxNXx8a2FiYWJ8ZW58MHx8fHwxNzUzNDI1ODI4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/hara-bhara-kabab.mp4',
    dataAiHint: 'hara bhara kabab',
    category: 'starters',
    ingredients: ['Spinach', 'Peas', 'Herbs'],
  },
  {
    id: 5,
    name: 'Tandoori Prawns',
    description: 'Fresh prawns marinated in tandoori spices and grilled to smoky perfection.',
    price: 350,
    image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxwcmF3bnN8ZW58MHx8fHwxNzUzNDI1NTA2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/tandoori-prawns.mp4',
    dataAiHint: 'tandoori prawns',
    category: 'starters',
    ingredients: ['Prawns', 'Tandoori Spices'],
  },
  // Main Course (Veg)
  {
    id: 6,
    name: 'Paneer Butter Masala',
    description: 'Soft paneer cubes in a creamy tomato-based gravy with butter and spices.',
    price: 240,
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2023/07/paneer-butter-masala-recipe.jpg',
    video: 'https://cdn-useast1.kapwing.com/teams/68853ec45e8cd4a3b32c9e24/jobs/6885417680e9445c535fa2f5/final_68853ec5f87e48c9a74055bc_857840.mp4?GoogleAccessId=prod-sa-videoprocessing%40kapwing-prod.iam.gserviceaccount.com&Expires=1753592324&Signature=fTbl3AtWIqbmimS4bRmWT4cVjjcobaJLQM4SXJWBh1PNiodSX5ltIQkfb%2BO2EE4QaWsDOKvdD8Em38QqpLK6ZBpydpiNPbR%2BC6lN11YXH9CLdnMMKyDwgPOyzxUH3E%2FwSyq2ta0AC%2BgIdqMzS96QFk%2BxssIArc6yQwsRR5TGGbFG5CGIZ6F6BCVo5%2Fr0121fsC8xXeoNM%2Bm02EGr%2F3HW4ogzN1N%2B7tULHAiCNx5NuwtpafpQIy0sKNb3XgCnUURwJFQOwYwr5yeW4ZCr9kPB2cONrRadtiwIzBzBt2%2BcbRFiCB64RBv9YRndewRqaMC3NRDioCvntv4dV0IHGbUrnA%3D%3D#t=0.01',
    dataAiHint: 'paneer butter masala',
    category: 'main-veg',
    ingredients: ['Paneer', 'Tomato', 'Butter', 'Cream', 'Spices'],
  },
  {
    id: 7,
    name: 'Chole Masala',
    description: 'Punjabi-style spicy chickpeas cooked with onion-tomato masala.',
    price: 180,
    image: 'https://www.solara.in/cdn/shop/articles/Chole_curry.jpg?v=1711521756&width=2048',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/chole-masala.mp4',
    dataAiHint: 'chole masala',
    category: 'main-veg',
    ingredients: ['Chickpeas', 'Onion', 'Tomato', 'Spices'],
  },
  {
    id: 8,
    name: 'Mix Veg Curry',
    description: 'Seasonal vegetables cooked in a lightly spiced, rich curry base.',
    price: 190,
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2023/07/vegetable-curry-recipe.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/mix-veg-curry.mp4',
    dataAiHint: 'mix veg curry',
    category: 'main-veg',
    ingredients: ['Mixed Vegetables', 'Curry', 'Spices'],
  },
  {
    id: 9,
    name: 'Dal Makhani',
    description: 'Slow-cooked black lentils in butter and cream, flavored with kasuri methi.',
    price: 200,
    image: 'https://www.sharmispassions.com/wp-content/uploads/2012/05/dal-makhani7.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/dal-makhani.mp4',
    dataAiHint: 'dal makhani',
    category: 'main-veg',
    ingredients: ['Black Lentils', 'Butter', 'Cream', 'Kasuri Methi'],
  },
  {
    id: 10,
    name: 'Matar Mushroom',
    description: 'Peas and mushrooms in a light onion-tomato gravy.',
    price: 210,
    image: 'https://static.toiimg.com/photo/75534551.cms',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/matar-mushroom.mp4',
    dataAiHint: 'matar mushroom',
    category: 'main-veg',
    ingredients: ['Peas', 'Mushrooms', 'Onion', 'Tomato'],
  },
  // Main Course (Non-Veg)
  {
    id: 11,
    name: 'Butter Chicken',
    description: 'Tandoori chicken chunks in rich tomato-butter-cream gravy.',
    price: 280,
    image: 'https://vismaifood.com/storage/app/uploads/public/ad2/3c9/7ee/thumb__1200_0_0_0_auto.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/butter-chicken.mp4',
    dataAiHint: 'butter chicken',
    category: 'main-non-veg',
    ingredients: ['Chicken', 'Tomato', 'Butter', 'Cream'],
  },
  {
    id: 12,
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice layered with spicy chicken and slow-cooked in dum.',
    price: 260,
    image: 'https://images.unsplash.com/photo-1701579231305-d84d8af9a3fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwYmlyeWFuaXxlbnwwfHx8fDE3NTM1NjA1MzV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/biryani.mp4',
    dataAiHint: 'chicken biryani',
    category: 'main-non-veg',
    ingredients: ['Basmati Rice', 'Chicken', 'Spices'],
  },
  {
    id: 13,
    name: 'Mutton Rogan Josh',
    description: 'Kashmiri-style lamb curry simmered in aromatic spices.',
    price: 330,
    image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgpvrhP0XQkWl_0Ti2TRumM5D9HKUFLvUeTmvgFqingINqgmu7JqifyCsWyrz3NCUAg-YuqqJ6xPPlp0vpyKyg5C1iXgPrpzpJeptWQWZrfPoeUBQkFmjYeRUuDfUVcgqu9ugI8B5HxmS8/s1600/Mutton+Rogan+Josh+Recipe.JPG',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/rogan-josh.mp4',
    dataAiHint: 'rogan josh',
    category: 'main-non-veg',
    ingredients: ['Lamb', 'Spices', 'Yogurt'],
  },
  {
    id: 14,
    name: 'Fish Curry (Bengali Style)',
    description: 'Fish pieces cooked in mustard gravy with a hint of green chili.',
    price: 300,
    image: 'https://www.licious.in/blog/wp-content/uploads/2021/08/Mustard-Fish-Glory-Shot.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/goan-fish-curry.mp4',
    dataAiHint: 'fish curry',
    category: 'main-non-veg',
    ingredients: ['Fish', 'Mustard', 'Green Chili'],
  },
  {
    id: 15,
    name: 'Egg Curry',
    description: 'Hard-boiled eggs cooked in spicy masala gravy.',
    price: 180,
    image: 'https://www.spicebangla.com/wp-content/uploads/2024/08/Egg-Masala-Curry.webp',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/egg-curry.mp4',
    dataAiHint: 'egg curry',
    category: 'main-non-veg',
    ingredients: ['Eggs', 'Masala', 'Gravy'],
  },
  // Breads & Rice
  {
    id: 16,
    name: 'Butter Naan',
    description: 'Soft, fluffy leavened bread brushed with butter.',
    price: 50,
    image: 'https://i.ytimg.com/vi/H3tW-UFSojU/maxresdefault.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/naan.mp4',
    dataAiHint: 'butter naan',
    category: 'breads-rice',
    ingredients: ['Flour', 'Yeast', 'Butter'],
  },
  {
    id: 17,
    name: 'Tandoori Roti',
    description: 'Whole wheat flatbread baked in clay tandoor.',
    price: 25,
    image: 'https://orders.popskitchen.in/storage/2024/09/image-62.png',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/tandoori-roti.mp4',
    dataAiHint: 'tandoori roti',
    category: 'breads-rice',
    ingredients: ['Whole Wheat Flour'],
  },
  {
    id: 18,
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with cumin seeds and ghee.',
    price: 90,
    image: 'https://homepressurecooking.com/wp-content/uploads/2024/05/instant-pot-jeera-rice-recipe-simple-flavorful-1715664008.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/jeera-rice.mp4',
    dataAiHint: 'jeera rice',
    category: 'breads-rice',
    ingredients: ['Basmati Rice', 'Cumin Seeds', 'Ghee'],
  },
  {
    id: 19,
    name: 'Veg Pulao',
    description: 'Fragrant rice cooked with veggies and whole spices.',
    price: 120,
    image: 'https://i.ytimg.com/vi/AYkSNH5Sj4M/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBg-8ePE68YsFXI7LmAWrCInHTBcA',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/veg-pulao.mp4',
    dataAiHint: 'veg pulao',
    category: 'breads-rice',
    ingredients: ['Basmati Rice', 'Vegetables', 'Spices'],
  },
  {
    id: 20,
    name: 'Lachha Paratha',
    description: 'Multi-layered flaky flatbread.',
    price: 40,
    image: 'https://i.ytimg.com/vi/nMuvAuMI7bk/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCUwWvnHkbb_ISBPzf3-vAp8NhOUg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/lachha-paratha.mp4',
    dataAiHint: 'lachha paratha',
    category: 'breads-rice',
    ingredients: ['Whole Wheat Flour'],
  },
  // Beverages
  {
    id: 21,
    name: 'Masala Chaas',
    description: 'Spiced buttermilk with cumin and coriander.',
    price: 40,
    image: 'https://www.spiceupthecurry.com/wp-content/uploads/2020/07/masala-chaas-1.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/masala-chaas.mp4',
    dataAiHint: 'masala chaas',
    category: 'beverages',
    ingredients: ['Buttermilk', 'Cumin', 'Coriander'],
  },
  {
    id: 22,
    name: 'Sweet Lassi',
    description: 'Refreshing Punjabi yogurt drink with sugar and cardamom.',
    price: 60,
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/lassi.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/mango-lassi.mp4',
    dataAiHint: 'sweet lassi',
    category: 'beverages',
    ingredients: ['Yogurt', 'Sugar', 'Cardamom'],
  },
  {
    id: 23,
    name: 'Cold Coffee',
    description: 'Chilled coffee blended with milk and ice cream.',
    price: 80,
    image: 'https://mytastycurry.com/wp-content/uploads/2020/04/Cafe-style-cold-coffee-with-icecream.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/cold-coffee.mp4',
    dataAiHint: 'cold coffee',
    category: 'beverages',
    ingredients: ['Coffee', 'Milk', 'Ice Cream'],
  },
  {
    id: 24,
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime drink served sweet or salted.',
    price: 50,
    image: 'https://gunjanchopra.com/content/images/2022/08/FI-2.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/fresh-lime-soda.mp4',
    dataAiHint: 'fresh lime soda',
    category: 'beverages',
    ingredients: ['Lime', 'Soda'],
  },
  {
    id: 25,
    name: 'Masala Tea',
    description: 'Indian spiced tea with milk and cardamom.',
    price: 30,
    image: 'https://namhah.com/wp-content/uploads/2019/01/masala.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/masala-chai.mp4',
    dataAiHint: 'masala tea',
    category: 'beverages',
    ingredients: ['Black Tea', 'Milk', 'Spices'],
  },
  // Desserts
  {
    id: 26,
    name: 'Gulab Jamun (2 pcs)',
    description: 'Soft milk dumplings soaked in rose-flavored sugar syrup.',
    price: 60,
    image: 'https://tiffinplanet.ca/cdn/shop/files/shutterstock_1848714091.jpg?v=1704486263',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/gulab-jamun.mp4',
    dataAiHint: 'gulab jamun',
    category: 'desserts',
    ingredients: ['Milk Solids', 'Sugar', 'Rose Water'],
  },
  {
    id: 27,
    name: 'Rasgulla (2 pcs)',
    description: 'Bengali dessert made of spongy cottage cheese balls in light syrup.',
    price: 50,
    image: 'https://dukaan.b-cdn.net/700x700/webp/media/b8e9da30-6658-4efb-8b9a-96246a11d8a8.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/rasgulla.mp4',
    dataAiHint: 'rasgulla',
    category: 'desserts',
    ingredients: ['Cottage Cheese', 'Sugar Syrup'],
  },
  {
    id: 28,
    name: 'Kesar Pista Kulfi',
    description: 'Traditional Indian ice cream infused with saffron and pistachios.',
    price: 70,
    image: 'https://images.archanaskitchen.com/images/recipes/indian/sweet-recipes/Kesar_Pista_Kulfi_Recipe_Indian_Ice_Cream_1_2_bd6850d070.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/kulfi.mp4',
    dataAiHint: 'kesar pista kulfi',
    category: 'desserts',
    ingredients: ['Milk', 'Saffron', 'Pistachios'],
  },
  {
    id: 29,
    name: 'Gajar Ka Halwa',
    description: 'Grated carrot pudding slow-cooked in milk and ghee.',
    price: 80,
    image: 'https://www.whiskaffair.com/wp-content/uploads/2019/05/Gajar-Ka-Halwa-2-3.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/gajar-ka-halwa.mp4',
    dataAiHint: 'gajar ka halwa',
    category: 'desserts',
    ingredients: ['Carrots', 'Milk', 'Ghee'],
  },
  {
    id: 30,
    name: 'Rabri',
    description: 'Thickened milk dessert garnished with dry fruits.',
    price: 90,
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2020/10/rabri-rabdi.jpg',
    video: 'https://storage.googleapis.com/stabl-media/rasoi-raj/videos/rabri.mp4',
    dataAiHint: 'rabri',
    category: 'desserts',
    ingredients: ['Milk', 'Sugar', 'Dry Fruits'],
  },
];

    
    