import type { Category, Dish } from './types';
import { Soup, Sprout, Drumstick, Wheat, GlassWater, IceCream } from 'lucide-react';

export const categories: Category[] = [
  { id: 'starters', name: 'Starters', icon: Soup },
  { id: 'main-veg', name: 'Main Course (Veg)', icon: Sprout },
  { id: 'main-non-veg', name: 'Main Course (Non-Veg)', icon: Drumstick },
  { id: 'breads-rice', name: 'Breads & Rice', icon: Wheat },
  { id: 'beverages', name: 'Beverages', icon: GlassWater },
  { id: 'desserts', name: 'Desserts', icon: IceCream },
];

export const dishes: Dish[] = [
  // Starters
  {
    id: 1,
    name: 'Paneer Tikka',
    description: 'Marinated cottage cheese grilled in a tandoor with spices and yogurt.',
    price: 220,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/paneer-tikka.jpg',
    dataAiHint: 'paneer tikka',
    category: 'starters',
    ingredients: ['Paneer', 'Yogurt', 'Spices'],
  },
  {
    id: 2,
    name: 'Chicken Malai Tikka',
    description: 'Creamy chicken cubes marinated in cheese, cream, and cardamom.',
    price: 270,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/chicken-malai-tikka.jpg',
    dataAiHint: 'chicken malai tikka',
    category: 'starters',
    ingredients: ['Chicken', 'Cheese', 'Cream', 'Cardamom'],
  },
  {
    id: 3,
    name: 'Vegetable Spring Rolls',
    description: 'Crispy rolls stuffed with seasoned veggies and served with sweet chili sauce.',
    price: 180,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/samosa.jpg',
    dataAiHint: 'spring rolls',
    category: 'starters',
    ingredients: ['Mixed Vegetables', 'Flour', 'Sweet Chili Sauce'],
  },
  {
    id: 4,
    name: 'Hara Bhara Kabab',
    description: 'Spinach and peas patties blended with Indian herbs and shallow fried.',
    price: 160,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/hara-bhara-kabab.jpg',
    dataAiHint: 'hara bhara kabab',
    category: 'starters',
    ingredients: ['Spinach', 'Peas', 'Herbs'],
  },
  {
    id: 5,
    name: 'Tandoori Prawns',
    description: 'Fresh prawns marinated in tandoori spices and grilled to smoky perfection.',
    price: 350,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/tandoori-prawns.jpg',
    dataAiHint: 'tandoori prawns',
    category: 'starters',
    ingredients: ['Prawns', 'Tandoori Spices'],
  },
  // Main Course (Veg)
  {
    id: 6,
    name: 'Paneer Butter Masala',
    description: 'Soft paneer cubes in a creamy tomato-based gravy with butter and spices.',
    price: 240,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/palak-paneer.jpg',
    dataAiHint: 'paneer butter masala',
    category: 'main-veg',
    ingredients: ['Paneer', 'Tomato', 'Butter', 'Cream', 'Spices'],
  },
  {
    id: 7,
    name: 'Chole Masala',
    description: 'Punjabi-style spicy chickpeas cooked with onion-tomato masala.',
    price: 180,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/chole-masala.jpg',
    dataAiHint: 'chole masala',
    category: 'main-veg',
    ingredients: ['Chickpeas', 'Onion', 'Tomato', 'Spices'],
  },
  {
    id: 8,
    name: 'Mix Veg Curry',
    description: 'Seasonal vegetables cooked in a lightly spiced, rich curry base.',
    price: 190,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/mix-veg-curry.jpg',
    dataAiHint: 'mix veg curry',
    category: 'main-veg',
    ingredients: ['Mixed Vegetables', 'Curry', 'Spices'],
  },
  {
    id: 9,
    name: 'Dal Makhani',
    description: 'Slow-cooked black lentils in butter and cream, flavored with kasuri methi.',
    price: 200,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/dal-makhani.jpg',
    dataAiHint: 'dal makhani',
    category: 'main-veg',
    ingredients: ['Black Lentils', 'Butter', 'Cream', 'Kasuri Methi'],
  },
  {
    id: 10,
    name: 'Matar Mushroom',
    description: 'Peas and mushrooms in a light onion-tomato gravy.',
    price: 210,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/matar-mushroom.jpg',
    dataAiHint: 'matar mushroom',
    category: 'main-veg',
    ingredients: ['Peas', 'Mushrooms', 'Onion', 'Tomato'],
  },
  // Main Course (Non-Veg)
  {
    id: 11,
    name: 'Butter Chicken',
    description: 'Tandoori chicken chunks in rich tomato-butter-cream gravy.',
    price: 280,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/butter-chicken.jpg',
    dataAiHint: 'butter chicken',
    category: 'main-non-veg',
    ingredients: ['Chicken', 'Tomato', 'Butter', 'Cream'],
  },
  {
    id: 12,
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice layered with spicy chicken and slow-cooked in dum.',
    price: 260,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/biryani.jpg',
    dataAiHint: 'chicken biryani',
    category: 'main-non-veg',
    ingredients: ['Basmati Rice', 'Chicken', 'Spices'],
  },
  {
    id: 13,
    name: 'Mutton Rogan Josh',
    description: 'Kashmiri-style lamb curry simmered in aromatic spices.',
    price: 330,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/rogan-josh.jpg',
    dataAiHint: 'rogan josh',
    category: 'main-non-veg',
    ingredients: ['Lamb', 'Spices', 'Yogurt'],
  },
  {
    id: 14,
    name: 'Fish Curry (Bengali Style)',
    description: 'Fish pieces cooked in mustard gravy with a hint of green chili.',
    price: 300,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/goan-fish-curry.jpg',
    dataAiHint: 'fish curry',
    category: 'main-non-veg',
    ingredients: ['Fish', 'Mustard', 'Green Chili'],
  },
  {
    id: 15,
    name: 'Egg Curry',
    description: 'Hard-boiled eggs cooked in spicy masala gravy.',
    price: 180,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/egg-curry.jpg',
    dataAiHint: 'egg curry',
    category: 'main-non-veg',
    ingredients: ['Eggs', 'Masala', 'Gravy'],
  },
  // Breads & Rice
  {
    id: 16,
    name: 'Butter Naan',
    description: 'Soft, fluffy leavened bread brushed with butter.',
    price: 50,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/naan.jpg',
    dataAiHint: 'butter naan',
    category: 'breads-rice',
    ingredients: ['Flour', 'Yeast', 'Butter'],
  },
  {
    id: 17,
    name: 'Tandoori Roti',
    description: 'Whole wheat flatbread baked in clay tandoor.',
    price: 25,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/tandoori-roti.jpg',
    dataAiHint: 'tandoori roti',
    category: 'breads-rice',
    ingredients: ['Whole Wheat Flour'],
  },
  {
    id: 18,
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with cumin seeds and ghee.',
    price: 90,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/jeera-rice.jpg',
    dataAiHint: 'jeera rice',
    category: 'breads-rice',
    ingredients: ['Basmati Rice', 'Cumin Seeds', 'Ghee'],
  },
  {
    id: 19,
    name: 'Veg Pulao',
    description: 'Fragrant rice cooked with veggies and whole spices.',
    price: 120,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/veg-pulao.jpg',
    dataAiHint: 'veg pulao',
    category: 'breads-rice',
    ingredients: ['Basmati Rice', 'Vegetables', 'Spices'],
  },
  {
    id: 20,
    name: 'Lachha Paratha',
    description: 'Multi-layered flaky flatbread.',
    price: 40,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/lachha-paratha.jpg',
    dataAiHint: 'lachha paratha',
    category: 'breads-rice',
    ingredients: ['Whole Wheat Flour'],
  },
  // Beverages
  {
    id: 21,
    name: 'Masala Chaas',
    description: 'Spiced buttermilk with cumin and coriander.',
    price: 40,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/masala-chaas.jpg',
    dataAiHint: 'masala chaas',
    category: 'beverages',
    ingredients: ['Buttermilk', 'Cumin', 'Coriander'],
  },
  {
    id: 22,
    name: 'Sweet Lassi',
    description: 'Refreshing Punjabi yogurt drink with sugar and cardamom.',
    price: 60,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/mango-lassi.jpg',
    dataAiHint: 'sweet lassi',
    category: 'beverages',
    ingredients: ['Yogurt', 'Sugar', 'Cardamom'],
  },
  {
    id: 23,
    name: 'Cold Coffee',
    description: 'Chilled coffee blended with milk and ice cream.',
    price: 80,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/cold-coffee.jpg',
    dataAiHint: 'cold coffee',
    category: 'beverages',
    ingredients: ['Coffee', 'Milk', 'Ice Cream'],
  },
  {
    id: 24,
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime drink served sweet or salted.',
    price: 50,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/fresh-lime-soda.jpg',
    dataAiHint: 'fresh lime soda',
    category: 'beverages',
    ingredients: ['Lime', 'Soda'],
  },
  {
    id: 25,
    name: 'Masala Tea',
    description: 'Indian spiced tea with milk and cardamom.',
    price: 30,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/masala-chai.jpg',
    dataAiHint: 'masala tea',
    category: 'beverages',
    ingredients: ['Black Tea', 'Milk', 'Spices'],
  },
  // Desserts
  {
    id: 26,
    name: 'Gulab Jamun (2 pcs)',
    description: 'Soft milk dumplings soaked in rose-flavored sugar syrup.',
    price: 60,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/gulab-jamun.jpg',
    dataAiHint: 'gulab jamun',
    category: 'desserts',
    ingredients: ['Milk Solids', 'Sugar', 'Rose Water'],
  },
  {
    id: 27,
    name: 'Rasgulla (2 pcs)',
    description: 'Bengali dessert made of spongy cottage cheese balls in light syrup.',
    price: 50,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/rasgulla.jpg',
    dataAiHint: 'rasgulla',
    category: 'desserts',
    ingredients: ['Cottage Cheese', 'Sugar Syrup'],
  },
  {
    id: 28,
    name: 'Kesar Pista Kulfi',
    description: 'Traditional Indian ice cream infused with saffron and pistachios.',
    price: 70,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/kulfi.jpg',
    dataAiHint: 'kesar pista kulfi',
    category: 'desserts',
    ingredients: ['Milk', 'Saffron', 'Pistachios'],
  },
  {
    id: 29,
    name: 'Gajar Ka Halwa',
    description: 'Grated carrot pudding slow-cooked in milk and ghee.',
    price: 80,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/gajar-ka-halwa.jpg',
    dataAiHint: 'gajar ka halwa',
    category: 'desserts',
    ingredients: ['Carrots', 'Milk', 'Ghee'],
  },
  {
    id: 30,
    name: 'Rabri',
    description: 'Thickened milk dessert garnished with dry fruits.',
    price: 90,
    image: 'https://storage.googleapis.com/stabl-media/rasoi-raj/rabri.jpg',
    dataAiHint: 'rabri',
    category: 'desserts',
    ingredients: ['Milk', 'Sugar', 'Dry Fruits'],
  },
];
